# Generated by Django 2.2.15 on 2020-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pwInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('changelog', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=32)),
            ],
        ),
    ]
